apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # NGINX 파드를 선택
  ports:
    - protocol: TCP
      port: 80  # 외부에서 접근할 포트
      targetPort: 80  # NGINX 파드가 수신하는 포트
  type: LoadBalancer  # 외부에 노출시키기 위해 LoadBalancer 사용 (NodePort로 변경 가능)
