apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream tomcat {
            server tomcat-service:8080;  # Tomcat 서비스로 요청 전달
        }

        server {
            listen 80;

            location / {
                proxy_pass http://tomcat;  # Tomcat 서비스로 로드밸런싱
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }
