apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1  # NGINX는 하나의 인스턴스만 실행
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # 최신 NGINX 이미지 사용
        ports:
        - containerPort: 80  # NGINX가 수신할 포트
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf  # NGINX 설정 파일을 ConfigMap에서 마운트
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config  # 앞서 생성한 ConfigMap 이름
